# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-galileo:
    runs-on: galileo
    
    steps:
    - uses: actions/checkout@v2

    - name: run-tests
      run: |
           source share/spack/setup-env.sh 
           spack uninstall dla-future
           spack clean -a 
           spack install -v --test=root --log-file=tests.log ~cuda ^intel-mkl ^hpx~cuda max_cpu_count=128 ^openmpi@3.1.0
           grep -A 80 "Running tests" tests.log
           
