# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-galileo:
    runs-on: galileo
    
    steps:
    - uses: actions/checkout@v2

    - name: run-tests
      run: |
           source /galileo/home/userinternal/clatini0/spack/spack/share/spack/setup-env.sh
           ls $GITHUB_WORKSPACE
           if [ `spack repo list| grep -c  dlaf` -eq 1 ]; then spack repo remove dlaf ; fi
           spack repo add $GITHUB_WORKSPACE/spack
           rm -f spack.log
           if [ `spack find | grep -c  dla-future` -eq 1 ]; then spack uninstall -y --all dla-future ; fi
           spack clean -a 
           spack install -v --test=root dla-future-ci ~cuda ^intel-mkl ^hpx~cuda max_cpu_count=128 ^openmpi@3.1.0 2>&1 | tee spack.log
           spack uninstall -y --all dla-future-ci;
           spack repo remove dlaf
           echo "==== TEST OUTCOMES ===="
           grep -A 80 "Running tests" spack.log
           
